# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
# This example is compatible with Dynamixel using protocol 2.0
left_motor:
  ID: 105
  Return_Delay_Time: 0
  Operating_Mode: 1
  Profile_Acceleration: 100
  Profile_Velocity: 10000
right_motor:
  ID: 104
  Return_Delay_Time: 0
  Operating_Mode: 1
  #Drive_Mode: 4
  Profile_Acceleration: 100
  Profile_Velocity: 10000
